### ISSUE TITLE
Django admin

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#10]
Take the look at the website on going to django admin website didn't work properly. Either you have to start from login page or you land up at home.

**Comment by Shubhanshuarya** [comment]
Hi Preeti,
Django Admin is working properly when I am opening this [Link](https://cityonbikes.herokuapp.com/admin/login/?next=/admin/)

Can you please describe this problem briefly? So, I can try to remove this Issue asap.

**Comment by preeti13456** [comment]
On the site itself when you go the django admin the site not work properly you have to login again. So i am looking for that issue. I would recommend you to first go through the website.

**Comment by Shubhanshuarya** [comment]
In this project, you are using Django 2.0 Version. If we are using python 3.6 and above version, it is highly recommended to use Django 3.0 Version or above. I am done with the upgraded version and successfully converted the whole project to Django 3.1.4 Version. Now, Admin and Login page is working properly.

![image](https://user-images.githubusercontent.com/45733409/103482758-a16e5700-4e08-11eb-915d-7bb69bf67836.png)

**Output::**

![image](https://user-images.githubusercontent.com/45733409/103482765-b6e38100-4e08-11eb-8e2f-6b7263fdade4.png)

![image](https://user-images.githubusercontent.com/45733409/103482767-be0a8f00-4e08-11eb-9e0f-7578e22c0efa.png)

**Comment by Shubhanshuarya** [comment]
Kindly Assign me, I will do it.

**Comment by preeti13456** [comment]
Sure
