### ISSUE TITLE
Bikes List Page #SWOC2021

### ISSUE THREAD

**Issue by TrushaT** [preeti13456/CityonBikes#13]
Description: Instead of a modal, the user can view a proper list of all bikes when he clicks bikes on the navbar.

**Comment by preeti13456** [comment]
Yes, can you implement it?

**Comment by TrushaT** [comment]
Yes, I am an intermediate Django developer.  I think creating a Bike model instead of available_bikes models and adding availability as a field. If you do not want that, I can add some more fields to available_bikes for more info of bike and list them. Whichever is suitable to u .

**Comment by preeti13456** [comment]
Cool, first approach is better work on that.

**Comment by preeti13456** [comment]
But you can't open the issue wait

**Comment by preeti13456** [comment]
Please comment on the new issue . I can assign it to you after that only.
