### ISSUE TITLE
Bikes List Page #SWoC30

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#14]
Adding functionalities on bike button present on the website

**Comment by TrushaT** [comment]
Pls, assign me this issue.

**Comment by himanshu007-creator** [comment]
if it doesnt work, i will like to work on it

**Comment by preeti13456** [comment]
Sure @TrushaT  pls update the status here, whether you can do this or not?

**Comment by TrushaT** [comment]
I am almost done. Backend is done. I am working on frontend that's all. We will make a PR soon

**Comment by TrushaT** [comment]
Backend is done. Just working on front end.  Will make a PR soon

**Comment by kishankr7979** [comment]
@preeti13456 Hey, We can also add the dynamic selection of bikes for the user, using the hyperlinked icons of Scooters/Sports/cruiser etc, if you are interested would you please ping me with the same so that i can contribute to this repo for an exponential growth.

**Comment by preeti13456** [comment]
Good point @kishankr7979

**Comment by preeti13456** [comment]
@TrushaT take into consideration these suggestions as well. And make the contribution by tomorrow. So that everyone will get the gair chance.

**Comment by kishankr7979** [comment]
@preeti13456 Open an another issue for the same, it would be great then.

**Comment by preeti13456** [comment]
I have opened the other duplicate issue. Kindly have a look @kishankr7979
