### ISSUE TITLE
Script Winter Of Code 

### ISSUE THREAD

**Issue by akrish4** [preeti13456/CityonBikes#2]
As you have registeree this oroject in SWOC , so I would like to contribute to this project , let me know what are the improvements needed for this web app.
Kindly let mw know and assign me @preeti13456 
Thank you

**Comment by preeti13456** [comment]
Surely let me know what domain you want to work in for backend part there is payments intergration gateway, in frontend part you can make the site more dynamic as currently it looks more static and for deployment you can try to integrate it on localhost without heroku integration included.

**Comment by akrish4** [comment]
@preeti13456  okay , i would like to work on front end part , i will use bootstrap to make it responsive and try to make slight changes in UI , i will integrate on localhost , but how  can i show you the final look of the project ? like images of output  will be fine or not ?  so thata the new chanages you can upload to heroku ?

**Comment by preeti13456** [comment]
Create a separate issue for the same. And try to first post the output I'll verify and will tell you the changes than you can push it to the branch and I'll merge it.

**Comment by akrish4** [comment]
@preeti13456  open a new issue - the front end part and assign me that issue.
do assign that new issue  and close when the project is completed.
I think we need to wait till jan 4 , the SWOC community guidlines are not yet released
