### ISSUE TITLE
Bikes List Page #SWoC30

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#21]
Adding functionalities on bike button present in the website using html, css, js functionalities.

**Comment by kishankr7979** [comment]
@preeti13456 will you please add the Tech Stack in a description, because it becomes difficult to overwrite the code and reusability of code becomes over-whelming

**Comment by kishankr7979** [comment]
P.S : i'm a MERN Developer

**Comment by preeti13456** [comment]
Okay sure. You interested in issue?

**Comment by kishankr7979** [comment]
@preeti13456 Yup, for the front-end part i'll but in case of back-end you are using Django which is not known for me

**Comment by preeti13456** [comment]
Cool work on frontend part.

**Comment by kishankr7979** [comment]
@preeti13456 hey, done with the categoryofBikes redirect page, but not able to open a new PR, even not able to push the changes to the forked repo, it says permission denied wil you please grant me the same

**Comment by kishankr7979** [comment]
![Screenshot 2021-01-05 at 11 30 07 PM](https://user-images.githubusercontent.com/41482800/103681842-ff886f00-4fad-11eb-8ca7-d1d44f32b154.png)
The selection of any categories will redirect to payment page.

**Comment by preeti13456** [comment]
Clone your forked repo instead of original, push to it, create pull request button on your repo wait fr me to accept it

**Comment by preeti13456** [comment]
It will not happen again but if still error persist try to ise --force and --all

**Comment by preeti13456** [comment]
And good work but make the cost on the bottom bar or something because it's not looking good on image.

**Comment by kishankr7979** [comment]
@preeti13456 its a responsive with some Animation hover

**Comment by kishankr7979** [comment]
that's why written price above image, let me commit it first then you'll get to feel the exact page

**Comment by preeti13456** [comment]
Okay then it's fine
