### ISSUE TITLE
Remove unwanted duplicate files and folder containing duplicated files #SWoC30

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#29]
Go to repo pull it into your local machine, create new ranch delete unwanted files, make sure the project still runs the same way, commit your changes and push the new branch to remote lastly merge the new branch into the original and verify correct files going to be merge before deleted.
*Whosoever works on this issue efficiently get some brownie points from my side*.
Also, try to remove the  gitignore file before committing.

**Comment by aavishkarmishra** [comment]
Interested 
Please assign this issue to me.

**Comment by preeti13456** [comment]
Tell me your approach first?

**Comment by preeti13456** [comment]
I am assigning it to you but you have to tell me your approach first

**Comment by preeti13456** [comment]
Any update @aavishkarmishra ?

**Comment by TanweerulHaque** [comment]
Can I proceed with this issue ?? @preeti13456 I am an SWoC participant.

**Comment by preeti13456** [comment]
Sure
