### ISSUE TITLE
The front end part

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#3]
Make the website more dynamic and user friendly.

**Comment by akrish4** [comment]
kindly assign me @preeti13456

**Comment by harikishantk** [comment]
kindly assign me @preeti13456

**Comment by preeti13456** [comment]
I have assigned it already to @akrish4  so @harikishantk if you want to work on backend part for making payment gateway integration kindly let me know.

**Comment by harikishantk** [comment]
Yes, I would like to contribute to the backend part. Does this contribution come under SWOC?

**Comment by akrish4** [comment]
we need to wait till jan 5 for making our contribution marked in SWOC. @preeti13456 @harikishantk

**Comment by akrish4** [comment]
> Yes, I would like to contribute to the backend part. Does this contribution come under SWOC?





yes
 right @preeti13456

**Comment by preeti13456** [comment]
Yes

**Comment by preeti13456** [comment]
No actually @akrish4 try to do this front end part within 4-5 days after that i will assign it to @harikishantk .

**Comment by anshshankar** [comment]
I am intrested

**Comment by preeti13456** [comment]
Firstly discuss the approach here how will you proceed both @akrish4  and @anshshankar

**Comment by akrish4** [comment]
@preeti13456  I am using bootstrap to make it fully responsive and along with it i will be improving the header and footer.

**Comment by preeti13456** [comment]
Good try to do the changes in respective file itself @akrish4 . And before pushing send the screenshot here

**Comment by akrish4** [comment]
> Good try to do the changes in respective file itself @akrish4 . And before pushing send the screenshot here

sure

**Comment by anshshankar** [comment]
> Firstly discuss the approach here how will you proceed both @akrish4 and @anshshankar

I could use bootstrap, css to make the website look user friendly and Dynamic. 
I would do following things
1. Make a tabs column where in all main categories will be available to the user
2.  A carousel with wherein all major offers and promos for new user would be displayed
3. A minor changes in the all tabs
4. Additional some new pages such Faqs, etc
5. Rent bikes according to categories

**Comment by anshshankar** [comment]
Can I work on it

**Comment by preeti13456** [comment]
yes but try to send the output here before pushing and start the pr making from 10 Jan

**Comment by anshshankar** [comment]
sure

**Comment by akrish4** [comment]
@anshshankar  you can work on this  :)

**Comment by anshshankar** [comment]
@preeti13456 can i make afew changes to urls.py .
Such as after successful login the page is redirected to rent_now.html but can I redirect it to home.html and rent_now will be a tab
which will be opened after the user clicks on it.
Since This looks more interactive.

**Comment by preeti13456** [comment]
Sure

**Comment by anshshankar** [comment]
ok thanks

**Comment by anshshankar** [comment]
Hi @preeti13456 
**Progress Report :-**

**1) The Login Page has been modified with the addition of of buttons of fb/g+/twitter**

![Login - Google Chrome 30-12-2020 02_01_19](https://user-images.githubusercontent.com/69162366/103312538-67393a00-4a43-11eb-837f-834140ec4484.png)

**2) The Blue Print Has been made for the First Page (Regex.html)**

![Login - Google Chrome 30-12-2020 02_07_00](https://user-images.githubusercontent.com/69162366/103312696-da42b080-4a43-11eb-8fb6-48d86ae73ad6.png)

![Login - Google Chrome 30-12-2020 02_07_05](https://user-images.githubusercontent.com/69162366/103312701-de6ece00-4a43-11eb-912b-d05dc9d77bbe.png)

![Login - Google Chrome 30-12-2020 02_07_14](https://user-images.githubusercontent.com/69162366/103312712-e3cc1880-4a43-11eb-8951-f6052c5719bb.png)

![Login - Google Chrome 30-12-2020 02_07_24](https://user-images.githubusercontent.com/69162366/103312719-e7f83600-4a43-11eb-884d-54f62dea6082.png)

**Comment by preeti13456** [comment]
Good  work but in login page try to align forgot 
Password and sign up text and about the first page let me know guys is the background color will looking good. And any other suggestions for modifications.

**Comment by preeti13456** [comment]
And try to add forgot password before login.

**Comment by anshshankar** [comment]
ok

**Comment by Ajaykumar34** [comment]
I'm interested on this project

**Comment by preeti13456** [comment]
@anshshankar have started contributing and will send his pr after 3 jan. @Ajaykumar34 I will assign this issue to you afterwards till then you can tell any changed looking to modeified change. 
In the meantime look to other unassigned issues as well.

**Comment by Ajaykumar34** [comment]
I have Questions regarding this projects

**Comment by preeti13456** [comment]
Yes please ask, you can ping me on slack or linkledin.

**Comment by nporia** [comment]
I would like to work on it too.

**Comment by anshshankar** [comment]
ya @nporia , I am currently Working on it.
I would make pr by 10th Jan . After that you can work on it.

**Comment by preeti13456** [comment]
@anshshankar  make the pr as soon as possible

**Comment by anshshankar** [comment]
ya sure

**Comment by anshshankar** [comment]
@preeti13456  could you open an issue for each and every page of the project . As this makes this lightens up the programer's work and you could get your work done in short period of time, due to involment of many coders. And the website will more looks more awesome . You could Fix a theme for the website.  As I couldn't do much work due to time constraint from my side. I had Fully prepared About us page. If you Like You could pick That theme ,as that theme looks good for the project

**Comment by anshshankar** [comment]
As i have closely monitored this project for almost 1 and half week . I could understand the project very well .
And will soon available for contribution in span of 2 weeks ,Since there is event going on in my university , i couldn't do much to project. And I regret it.

**Comment by preeti13456** [comment]
Sounds cool. So I have created the issue for login page I'll create an issue for about us page as well.

**Comment by preeti13456** [comment]
Is that ok?

**Comment by anshshankar** [comment]
Ya you could create issue for it if you want, And also you should create issue for rent_bike ,Bikes ,Offers ,Contact us And Should create a new page for profile section

**Comment by preeti13456** [comment]
Rent_bikes and bikes have already been done check the repo. I'll create for contact us, offers a and profile section

**Comment by anshshankar** [comment]
ok
