### ISSUE TITLE
Changes on Login page #SWoC30

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#30]
Enhancement of the login button on the hope page by adding some CSS design. As well as create a forgot password button after in the login box.

**Comment by harikishantk** [comment]
I would like to work on it, after I finish the backend part. May I?

**Comment by preeti13456** [comment]
Yes but I have opened after the conversation with one of the participants, first I'll give him a chance to contribute after that you can also work on the issue with the changes.

**Comment by dollyjain51099** [comment]
I would like to work on this issue, please assign it to me!

**Comment by sanyajain26** [comment]
I would like to work on this issue, please assign it to me!

**Comment by preeti13456** [comment]
Tell me your approach first @dollyjain51099 @sanyajain26

**Comment by spursbyte** [comment]
i will like to work on it.
can you assign me

**Comment by preeti13456** [comment]
How will you approach?

**Comment by spursbyte** [comment]
i will add first css design to the login button ..preferebly crreating a padding around it and looking for some transparent design for the box around it.if it does'nt look convincing then will try to fill it with a color that would complement the background. then i will move on the forgot password part.

**Comment by preeti13456** [comment]
Cool

**Comment by kishankr7979** [comment]
@preeti13456 hey, can we move forward with express.js server only if you are not strict to the Django

**Comment by preeti13456** [comment]
This issue has been assigned already let's see the outcome first, if it still needs changes we can think about it.

**Comment by dollyjain51099** [comment]
I was also wondering about adding a couple of elements to the login template and make it look attractive using CSS.

**Comment by sanyajain26** [comment]
@preeti13456  Hey, I was thinking of styling the button with color contrast that goes with the background and can change the style of the button upon hovering, can also add some icon to it.

**Comment by preeti13456** [comment]
Sure good point

**Comment by sanyajain26** [comment]
Can you assign this to me so that I can start working?

**Comment by preeti13456** [comment]
I'll create a seprate issue fr the same. As it's already assigned.

**Comment by preeti13456** [comment]
Comment there I'll assign it to you.

**Comment by preeti13456** [comment]
Any updates @spursbyte ?

**Comment by spursbyte** [comment]
Yes it is almost complete but as per our discussion i have to undo the changes i have made to the login button..so that part is only left.And forgot password button is done.

**Comment by preeti13456** [comment]
Ok

**Comment by prajjwal1231** [comment]
Hey, @preeti13456 Assign this issue to me.

**Comment by preeti13456** [comment]
Some worlnhas already been done @prajjwal1231 so kindly make the changes accordingly.

**Comment by prajjwal1231** [comment]
Okay @preeti13456
