### ISSUE TITLE
Changes on about us page

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#31]
Make the about us page more dynamic and  enhanced. Share your approach in the comment section.

**Comment by pritamp17** [comment]
Mam i would like to work on this issue, could you please assign this to me? I  can make page more dynamic and responsive using media query..

**Comment by preeti13456** [comment]
Any updates @pritamp17

**Comment by pritamp17** [comment]
Mam I am working on it..I will send PR today.

**Comment by preeti13456** [comment]
Ok

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
