### ISSUE TITLE
Add responsiveness to the site #SWoC30

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#32]
For responsiveness and styling, you can use material design, tailwind css , or bootstrap.
Share your approach what will you go for and why?

**Comment by Sloth-Panda** [comment]
would like to take this issue

**Comment by Sloth-Panda** [comment]
I will use bootstrap to make this  as I am more comfortable with that but if you don't want to use that I can do it using css and media queries

**Comment by preeti13456** [comment]
There is some work done using bootstrap as well. I am comfortable as far as the changes are not affecting the website in a bad way. So make modification accordingly and also check that after modifyin g the website is working finely same on computer and android.

**Comment by Sloth-Panda** [comment]
![Screenshot (35)](https://user-images.githubusercontent.com/70213384/103861044-c56cb980-50e2-11eb-9e54-86cbc7553227.png)
![Screenshot (34)](https://user-images.githubusercontent.com/70213384/103861029-bdad1500-50e2-11eb-946b-7da5361f5dc6.png)


Are the stylesheets not linked properly? or what's the issue why I am seeing something like this on my local machine??

**Comment by preeti13456** [comment]
But I am saying the website perfectly working.

**Comment by preeti13456** [comment]
Ya it may be possible because I have deployed it using heroku and the images are not connecyed properly.

**Comment by Sloth-Panda** [comment]
Then what can I do ?? Like I can't see a perfect layout so how can I work and make it responsive?

**Comment by preeti13456** [comment]
Look into static files folder and static folder

**Comment by preeti13456** [comment]
Images are there only.

**Comment by Sloth-Panda** [comment]
Hey @preeti13456  I have messaged on the slack channel  check that out

**Comment by Sloth-Panda** [comment]
Hey @preeti13456  is the issue sorted??

**Comment by preeti13456** [comment]
Yes check once
