### ISSUE TITLE
Changes needed on website page

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#33]
on your hero, that's the header banner thing the background is repeating by default , use this css to fix that {
background-repeat: no-repeat;
background-size: cover; 
background-position: center;
}

**Comment by pritamp17** [comment]
Mam i would like to work on this issue,  could you please assign me this?

**Comment by preeti13456** [comment]
I can't assign you this issue as per person I can assign only one issue. But if you completed the assigned one I will assign this to you.

**Comment by sanyajain26** [comment]
I would like to work on this issue, please assign this to me @preeti13456

**Comment by sanyajain26** [comment]
Can you please specify which page you are talking about? @preeti13456

**Comment by preeti13456** [comment]
Well you can go through any website page here where you think there's a need of enhancement, and try to look into the changes already done with the frontend portion.

**Comment by preeti13456** [comment]
Any updates @sanyajain26 ?

**Comment by preeti13456** [comment]
Basically the changes are mainly needed for login page first.

**Comment by preeti13456** [comment]
Then we can move ahead to other pages. About us and rent bikes pages rae already sorted. So there you're left with some changes needed for offer, login.

**Comment by 96RadhikaJadhav** [comment]
@preeti13456  Can I work on the issue? If I can, then can you please let me know to which file first we can do the changes.

**Comment by preeti13456** [comment]
Yes surely will tell you.

**Comment by 96RadhikaJadhav** [comment]
@preeti13456  Any update on the above request?

**Comment by preeti13456** [comment]
Ya you can work on pages other than login, about us, rent bikes. But check the page which has not been changed from the template folder itself

**Comment by preeti13456** [comment]
And please tell me here whatare you going to work on and your approach as well?

**Comment by 96RadhikaJadhav** [comment]
@preeti13456  I'm thinking of working on home page styling. As it's a bit difficult to read the City on Bikes content as the font and background color are bit same. After this is done, will check other pages too and can update you about the same. Sounds good?

**Comment by 96RadhikaJadhav** [comment]
![image](https://user-images.githubusercontent.com/56536997/104627871-93002500-56bd-11eb-9fbc-abf04a8d0274.png)

Here is a screenshot for your reference. The content above sign up button. Please let me know if I can work on this.

**Comment by preeti13456** [comment]
Sure go ahead

**Comment by 96RadhikaJadhav** [comment]
@preeti13456  I have created a PR. Along with the styling I have also added some extra lines to the description of the City on Bikes project. Please review it and let me know if any changes needs to be undo.
