### ISSUE TITLE
Styling the login button

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#36]
styling the button with color contrast that goes with the background and can change the style of the button upon hovering, can also add some icon to it.

**Comment by Akshi149** [comment]
Hi @preeti13456 I would like to work on it.

**Comment by dollyjain51099** [comment]
I would like to work on this issue, kindly assign it to me!

**Comment by preeti13456** [comment]
Already assigned.

**Comment by sanyajain26** [comment]
I would like to work on this issue, assign it to me.

**Comment by preeti13456** [comment]
Is there any update @Akshi149

**Comment by Akshi149** [comment]
I was having viva from past two days. Will surely do it in the next day or two

**Comment by preeti13456** [comment]
Ok from next to me tell me in prior

**Comment by 96RadhikaJadhav** [comment]
@preeti13456  Can I work on the issue?

**Comment by preeti13456** [comment]
Sure
