### ISSUE TITLE
Feature request: add calling functionality through internet SWoC30

### ISSUE THREAD

**Issue by Abhijay007** [preeti13456/CityonBikes#39]
**Is your feature request related to a problem? Please describe.**

If the user clicks on the given number on the site, then nothing happens, he/she needs to dial it manually. I want to implement a functionality that whenever the user clicks on the number the call will automatically dial from his/her mobile

**Describe the solution you'd like**

 we just need to add an HTML anchor tag and need to set hyper reference( href ) to "tel: given number"

- Add any other context or screenshots about the feature request here.

![2021-01-08 (3)](https://user-images.githubusercontent.com/64387054/104036813-e3790d80-51f9-11eb-9704-5d163492e66d.png)

example in gif format 

![city on bike](https://user-images.githubusercontent.com/64387054/104037342-9ba6b600-51fa-11eb-8885-fed807ee6fcc.gif)

**Comment by preeti13456** [comment]
Add this feature as well as check if it's visible on Android as well.

**Comment by preeti13456** [comment]
And before opening ask to raise this issue otherwise it will be difficult to enter in one of teh swoc contribution.

**Comment by Abhijay007** [comment]
> Add this feature as well as check if it's visible on Android as well.

@preeti13456  ma'am, it automatically shows the active devices(connected) on the webpage and triggers call on its own.

**Comment by preeti13456** [comment]
ok then go ahead
