### ISSUE TITLE
The backend integration

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#4]
Make a payment gateway backend on the site.

**Comment by harikishantk** [comment]
Yes, I would like to contribute to the backend part. Kindly label this issue under "SWOC".

**Comment by preeti13456** [comment]
How much have you done?

**Comment by preeti13456** [comment]
I have updated some files try to create the backend according to them. Remove the duplicate files and folder containing duplicate files and integrate them in original folders.

**Comment by harikishantk** [comment]
> 
> 
> How much have you done?

I haven't started yet, I was waiting for front-end issues  to get finished so that I complete the payment part. I'll start it right away.

**Comment by harikishantk** [comment]
> 
> 
> I have updated some files try to create the backend according to them. Remove the duplicate files and folder containing duplicate files and integrate them in original folders.

Okay, mam, I'll do it.

**Comment by preeti13456** [comment]
Yes frontend is almost ready. I'll merging the files you can start your work on backend part.

**Comment by preeti13456** [comment]
You can start the backend.

**Comment by preeti13456** [comment]
Do the backend integration by taking in the changes already done to the site check o the templates folder and do the changes accordingly. It has been 10 days

**Comment by SinghShreya05** [comment]
Ma'am I would like to contribute. Please assign me.

**Comment by preeti13456** [comment]
Is there any update @SinghShreya05 ?

**Comment by SinghShreya05** [comment]
> Is there any update @SinghShreya05 ?

There's a slight hiccup in integration process, in order to settle the payment received and setting up the integration process, Ma'am I'm texting you on slack regarding this,

**Comment by preeti13456** [comment]
Sure

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kishankr7979** [comment]
Hey @preeti13456 do we have any update regarding the payment gateway? i can suggest a good idea for the same

**Comment by kishankr7979** [comment]
We can go for a Razorpay's payment gateway

**Comment by preeti13456** [comment]
Yes we are working on that approach.

**Comment by preeti13456** [comment]
Any progress @SinghShreya05

**Comment by SinghShreya05** [comment]
Ma'am I've sent a PR, kindly review and merge it. And please let me know if anything else needs to be done. Thank you. @preeti13456

**Comment by preeti13456** [comment]
No it was good but can you help me in finding a geocoding api?

**Comment by SinghShreya05** [comment]
@preeti13456 Sure Ma'am, I'll like to work on this.
