### ISSUE TITLE
UI changes SWoC20

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#42]
Improving the UI of the website.

**Comment by gmnikhil** [comment]
#41

**Comment by patelaryan7751** [comment]
@preeti13456 i want to work on this.

**Comment by preeti13456** [comment]
It's already assigned wait for 5 days . Till it get assigned to you in the meantime you can explore the website fix some bugs or raise issue and can provide any valuable feedback to this issue as well.
