### ISSUE TITLE
SMTP server #SWoC30

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#49]
SMTP server for sending welcome email after signup

**Comment by pritamp17** [comment]
@preeti13456 mam i want to try working on this issue ,as i have worked on smtp libarary before ,could you assign me this?

**Comment by preeti13456** [comment]
Sure

**Comment by preeti13456** [comment]
Update?

**Comment by pritamp17** [comment]
mam I'm working on it

**Comment by pritamp17** [comment]
@preeti13456 mam I was able to send mail on successfully registering with SMTP but, the account from which we will be sending mail should enable "allow less secured device" option.will that be fine?

**Comment by preeti13456** [comment]
No that will be an issue.  Because the user has to enable advanced options and what if the feature didn't work out on android. Issues of cookies can also be there. Did you test it?

**Comment by pritamp17** [comment]
yes, mam, I tested it the one who will send the mail only has to enable allow secure apps, the receiver doesn't, and also received an email on android there was no other issue I encountered.

**Comment by preeti13456** [comment]
Ok then

**Comment by pritamp17** [comment]
mam, should I send PR then?

**Comment by preeti13456** [comment]
Yes please
