### ISSUE TITLE
README update 

### ISSUE THREAD

**Issue by Aniket118** [preeti13456/CityonBikes#5]
very little information has been provided in README. 
Ex: how to run the setup is missing and a little description about the project. @preeti13456 it will be nice of you if can do that. 
And can you provide any group link to have a discussion over the issue.

**Comment by preeti13456** [comment]
Sure

**Comment by preeti13456** [comment]
Tell me if you want to work on this issue @Aniket118

**Comment by Aniket118** [comment]
I mainly don't know much about the project. But README for the setup and if a workflow can be described then I can look into it.

**Comment by preeti13456** [comment]
Link of the website is on the description of the project you can check there. And if you have any further doubts you can ping me on slack.

**Comment by preeti13456** [comment]
@akrish4 let me know your availability on this issue

**Comment by Aniket118** [comment]
ok thankyou!

**Comment by akrish4** [comment]
> @akrish4 let me know your availability on this issue



> I mainly don't know much about the project. But README for the setup and if a workflow can be described then I can look into it.

yes @preeti13456  , i can work on this issue , if @Aniket118  doesn't know much about the project.
`kindly assign me`

**Comment by preeti13456** [comment]
Cool

**Comment by preeti13456** [comment]
Openeup by someone else
