### ISSUE TITLE
Frontend Integration #SWoC40

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#51]
Check all the files of the modified frontend pages of home, login, about us, offer, and others and integrate them with the source code. This will help to reduce the complexity of our app as well as help to run it on other devices with ease. As well as try to remove the codes if they are visible on the pages.
Will guarantee browny points for an efficient solution

**Comment by nilisha-jais** [comment]
I want to contribute in this issue(participant of SWoC'21)

**Comment by preeti13456** [comment]
You can contribute to any one issue one at at a time.

**Comment by preeti13456** [comment]
So decide and tell me which issue you want to work upon?

**Comment by preeti13456** [comment]
Hey @nilisha-jais can you work on this issue?

**Comment by nayaldivya** [comment]
Hi @preeti13456, can you please assign this issue to me?

**Comment by nayaldivya** [comment]
Thanks @preeti13456. Can you please provide me some resources so that i can come up with an efficient solution.

**Comment by preeti13456** [comment]
I don't have specific docs as such. But I think @akrish4 can help you in providing guidance for setting up and other resources. As he has already familiar with the website.

**Comment by preeti13456** [comment]
Update?

**Comment by nayaldivya** [comment]
@preeti13456 I've set up the project on my system and currently researching through the issue. This is first time for me working on frontend integration hence it's going a little tough for me.

**Comment by preeti13456** [comment]
Sure, take your time

**Comment by nayaldivya** [comment]
Hi @preeti13456, can you please brief me again about this issue. Some hints and pointers would be very helpful.  I was trying to understand the codebase and do some research about frontend integration all this time.

**Comment by preeti13456** [comment]
I can assign you one issue at a time only @nayaldivya . Since you're facing problem resolving this issue after so much time given to you . I will be unassigning this issue.

**Comment by nayaldivya** [comment]
I understand @preeti13456. Thanks for your time.

**Comment by Kathuria** [comment]
@preeti13456 : Can I try work on this integration?

**Comment by preeti13456** [comment]
Sure

**Comment by Kathuria** [comment]
@preeti13456 : While installing and setting up this repo, faced
django 3.1.4 requires asgiref<4,>=3.2.10, but you'll have asgiref 3.2.7 which is incompatible.

I updated in requirements **asgiref 3.2.10**, Can I commit as well?

and can we update in documentation that project won't work with **python 3.9.1**, it should be <=3.8.x 
{Reason The current psycopg2 implementation supports:

Python version 2.7
Python 3 versions from 3.4 to 3.8}

Ref: https://www.psycopg.org/docs/install.html

**Comment by Kathuria** [comment]
@preeti13456 : As part of frontend integration, In first step, I integrated PasswordRetrivalForm creating forgot - password templates and adding URL.
Next I found missing favicon on website, even in deployed site - As initial step adding favicon in separate commit - Please consider that as frontend int. or can open new issue.

**Comment by Kathuria** [comment]
@preeti13456 : Cleaned up styles, Please check PR's

**Comment by Kathuria** [comment]
@preeti13456 : Modified Offers Template, Please check

**Comment by Kathuria** [comment]
@preeti13456 : I validated most of links and its working now, not able to link rent_now and related flows - Please validate above PR's and can assign to next contributor for more updates.
Thanks.

**Comment by Kathuria** [comment]
> @preeti13456 : While installing and setting up this repo, faced
> django 3.1.4 requires asgiref<4,>=3.2.10, but you'll have asgiref 3.2.7 which is incompatible.
> 
> I updated in requirements **asgiref 3.2.10**, Can I commit as well?
> 
> and can we update in documentation that project won't work with **python 3.9.1**, it should be <=3.8.x
> {Reason The current psycopg2 implementation supports:
> 
> Python version 2.7
> Python 3 versions from 3.4 to 3.8}
> 
> Ref: https://www.psycopg.org/docs/install.html

Thanks for consideration- Noticed updated Documentation for python ver. i.e. 3.7 and updated requirements.txt as well.
