### ISSUE TITLE
Welcome bot #SWoC40

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#52]
Create a bot that will open up a pull requests as a project admin, as well as can create an issue. The bot is also responsible to send a welcome message for each contribution automatically.

**Comment by Vrindagupta6828** [comment]
@preeti13456 please assign this issue to me.

**Comment by Vrindagupta6828** [comment]
@preeti13456 listen do we have to give welcome messages when a pr is raised or issue is created or contribution is done? As how can a bot create issue or open pull request?

**Comment by preeti13456** [comment]
You have to create welcome message for contribution, and rge issue is created andveaise by project adminnonly so you have to set it accordingly

**Comment by Vrindagupta6828** [comment]
Can you elaborate??does it mean that if any other user or contributor will raise an issue he will not be able to

**Comment by preeti13456** [comment]
He/she can definitely raise but it will not be counted for contribution.

**Comment by Vrindagupta6828** [comment]
Can you please share some link for my help as i am unable to understand what exactly the bot will do.

**Comment by preeti13456** [comment]
Ok np @akrish4 I will be assigning this issue to you.

**Comment by akrish4** [comment]
Kindly assign me @preeti13456

**Comment by preeti13456** [comment]
Updates?

**Comment by akrish4** [comment]
yes I will open the pr soon

**Comment by akrish4** [comment]
#62   PR
