### ISSUE TITLE
A setup.md file for setting the django project after cloning it #SWoC30

### ISSUE THREAD

**Issue by harsh7in** [preeti13456/CityonBikes#58]
As there are many beginners who want to contribute to the project but they usually have trouble while setting the project.
so there will be step by step process to run the project after cloning it.

**Comment by nayaldivya** [comment]
Hi @preeti13456, Since I've already set the project on my system, I know it well and can solve this issue.

**Comment by nayaldivya** [comment]
Hi @preeti13456, should I name the file setup.md or SETUP.md?

**Comment by preeti13456** [comment]
The former one

**Comment by nayaldivya** [comment]
Hi @preeti13456, I made a PR. Have a look and tell me if any changes you need.
