### ISSUE TITLE
Changes on login page

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#60]
Remove overlapping on https://cityon.herokuapp.com/loginPage/?next=/rent_now/ this page

**Comment by nehaparmar99** [comment]
Can I work on this under SWoC'21?

**Comment by preeti13456** [comment]
Sure

**Comment by nehaparmar99** [comment]
Ma'am do you only want the the overlapping texts to be taken care of or want a redesign of the form as well?

**Comment by preeti13456** [comment]
Firstly I want only overlapping to be removed. After then we can see if the design is required Or not.

**Comment by nehaparmar99** [comment]
<img width="1440" alt="Screenshot 2021-01-18 at 9 32 22 PM" src="https://user-images.githubusercontent.com/48972593/104938598-4ece9680-59d5-11eb-9bb1-015dc7b4393a.png">
Ma'am is this okay?

**Comment by preeti13456** [comment]
Yes perfect

**Comment by nehaparmar99** [comment]
Is anything else required or should I make a PR then?

**Comment by preeti13456** [comment]
Make the pr

**Comment by nehaparmar99** [comment]
Sure maam.Just wanted to know how many points this adds on my SWoC.
