### ISSUE TITLE
Changes needed Home Page

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#61]
Require to remove the red font slider page on the home page. Website Link: https://cityon.herokuapp.com/. Remove the already available code file when pushing a commit.

**Comment by preeti13456** [comment]
As well as the background image is also not right. Need modification

**Comment by TanweerulHaque** [comment]
I can work on this issue mam. @preeti13456 . What are all the changes needed to be done ?? Should I make that font colour white as in the next image of the carousel?? And Do I need to change the background image too ?? I am an SWoC participant.

**Comment by preeti13456** [comment]
No, just delete the first slider containing red font, as the content is same in both, then the background image of the home page should be the one containing bike in background so make it accordingly and do the changes from  in the given code itself not create the other file Or folder.

**Comment by TanweerulHaque** [comment]
I have sent a PR. Please review it. @preeti13456
