### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#7]
Update the README file with appropriate documentation and resources. That will tell the purpose of website as well as future scope if any.

**Comment by akrish4** [comment]
@preeti13456  kindly assign me 
I will update README file and add code of conduct file also

**Comment by preeti13456** [comment]
Code of conduct is already been added, Try to update the README file looking into changes already been done, as soon s possible.

**Comment by akrish4** [comment]
#26 PR
