### ISSUE TITLE
Adding functionalities

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#8]
Add functionalities to the button to select your bike and add your cart

**Comment by Adarsh88** [comment]
Hey I would like to contribute to this project. Can you assign this to me ?

**Comment by preeti13456** [comment]
Sure, but share your approach first before sending pr.

**Comment by Adarsh88** [comment]
Okay, we can discuss it in slack right ?

**Comment by preeti13456** [comment]
Ya sure

**Comment by Ajaykumar34** [comment]
i'm interested on this project

**Comment by preeti13456** [comment]
How much have you done?

**Comment by preeti13456** [comment]
Do the changes according to the modifications in the project.

**Comment by Ajaykumar34** [comment]
yes i need some time but i'm working on html,css,javascript not for django .if you ok with it then you giving a response to me.

**Comment by preeti13456** [comment]
Ok

**Comment by Ajaykumar34** [comment]
i'll give you demostratation how location will work on our project.

**Comment by preeti13456** [comment]
Cool

**Comment by preeti13456** [comment]
@Ajaykumar34 you have today only to submit the work progress. It's been 7 days now please report your work.

**Comment by Ajaykumar34** [comment]
ok i'll submit the report as soon as

**Comment by Ajaykumar34** [comment]
hello mam there is some problem with api so at this time i can't convert latitude and longlitude to the formatted address.
but i have genrates latitudes and longlitudes of our current location.it will show in console

**Comment by Ajaykumar34** [comment]
i'll added the code on your rent_now.html

**Comment by preeti13456** [comment]
Is this problem occuring due to the recent changes in the frontend?

**Comment by Ajaykumar34** [comment]
no, i  have nothing change in your frontend and i have only written js code only

**Comment by Ajaykumar34** [comment]
but if api work properly i'll added new html and css file for pick a location.

**Comment by preeti13456** [comment]
Okay so for now only some work has been done for this issue. Did you created the or for the same??

**Comment by Ajaykumar34** [comment]
firstly i have to check api work  properly in our project , then i will move to the next part of the functionality

**Comment by preeti13456** [comment]
Pull request

**Comment by Ajaykumar34** [comment]
ok

**Comment by Ajaykumar34** [comment]
please check the pull request

**Comment by preeti13456** [comment]
Didn't received any

**Comment by Ajaykumar34** [comment]
ok check it again

**Comment by preeti13456** [comment]
Cool but currently this issue has not been resolved completely right?

**Comment by Ajaykumar34** [comment]
yes, i'm working on it the api  is used for genrating formatted address but the api having some problem.

**Comment by preeti13456** [comment]
I have assigned it to @Adarsh88 , he will take it from here @Ajaykumar34  is that will be okay with you?

**Comment by Ajaykumar34** [comment]
so tell me mam which part i'm working on this project

**Comment by preeti13456** [comment]
I'll reassign you this issue after 4-5 days from now if the issue not resolved. Till that you can help @Adarsh88 on this issue aa well as contribute to some other  issues as well.

**Comment by Ajaykumar34** [comment]
okk

**Comment by Ajaykumar34** [comment]
hello mam i need help who is mentor of this project.

**Comment by Ajaykumar34** [comment]
the issues is almost solved

**Comment by Ajaykumar34** [comment]
hello mam my work is done

**Comment by preeti13456** [comment]
Please create a pr with as if you can

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Ajaykumar34** [comment]
please check

**Comment by Ajaykumar34** [comment]
temporary i have printed formatted address in the paragraph section

**Comment by preeti13456** [comment]
Good work @Adarsh88

**Comment by preeti13456** [comment]
Good work @Ajaykumar34
