### ISSUE TITLE
Launch Website command 

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/CityonBikes#9]
Create an automation command to launch the website from cli .

**Comment by himanshu007-creator** [comment]
HI @preeti13456  mam.
I have worked on this issue. Please assign me this and check by PULL REQUEST.https://github.com/preeti13456/CityonBikes/pull/17

**Comment by preeti13456** [comment]
Good work.

**Comment by preeti13456** [comment]
Good work @himanshu007-creator . Look to other issues as well.
